name: Push run tests and deploy to Heroku

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instalando dependencias
        run: npm install
      - name: Instalando mocha
        run: npm install mocha
      - name: Ejecutando tests
        run: npm  test
        env:
          CI: true